Controllers/CandidateController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using AutoMapper;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Nust_Vote_System.Datalayer;
using Nust_Vote_System.DatatabaseModel;
using Nust_Vote_System.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Nust_Vote_System.Controllers
{
    public class CandidateController : Controller
    {
        private readonly VotingContext applicationDbContext;
        private readonly IMapper mapper;
        private readonly ILogger<AccountController> logger;
        private readonly INotyfService _notyf;
        private IWebHostEnvironment _Environment;

        public CandidateController(IWebHostEnvironment Environment, INotyfService notyf, VotingContext applicationDbContext, IMapper mapper, ILogger<AccountController> logger)
        {
            this.applicationDbContext = applicationDbContext;
            this.mapper = mapper;
            this.logger = logger;
            _notyf = notyf;

            _Environment = Environment;
        }

        [HttpGet]
        public IActionResult Index()
        {

            CadidatesViewModel movieView = new CadidatesViewModel();
            List<CadidatesViewModel> model = new List<CadidatesViewModel>();
            var rates = applicationDbContext.Candidates.ToList();

            var ratesModel = mapper.Map<IEnumerable<CadidatesViewModel>>(rates);

            CadidatesViewModelList detailsViewModel = new CadidatesViewModelList();

            detailsViewModel.Cadidates = new List<CadidatesViewModel>();

            detailsViewModel.Cadidates = (List<CadidatesViewModel>)ratesModel;

            return View(detailsViewModel);

        }


        public IActionResult Edit(int id)
        {


            try
            {
                if (id == 0)
                {
                    return BadRequest();
                }

                var rates = applicationDbContext.Candidates.FindAsync(id).Result;

                var ratesmodel = mapper.Map<CadidatesViewModel>(rates);
                return View(ratesmodel);
            }
            catch (Exception e)
            {
                logger.LogError(e.Message);
                return BadRequest();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Obsolete]
        public async Task<IActionResult> Edit(int id, CadidatesViewModel model)
        {
            if (id != model.Id)
            {
                return NotFound();
            }

            _notyf.Success("The movie has been Edited successfully..");
            Candidates userEntity = new Candidates();

            if (ModelState.IsValid)
            {
                try
                {
                    if (model.ImageFile != null)
                    {


                        string wwwRootPath = _Environment.WebRootPath;
                        string fileName = Path.GetFileNameWithoutExtension(model.ImageFile.FileName);
                        string extension = Path.GetExtension(model.ImageFile.FileName);
                        model.ImageName = fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                        string path = Path.Combine(wwwRootPath + "/Image/", fileName);

                        using (var fileStream = new FileStream(path, FileMode.Create))
                        {
                            await model.ImageFile.CopyToAsync(fileStream);
                        }

                        var CandidatesModel = mapper.Map<Candidates>(model);


                        applicationDbContext.Candidates.Update(CandidatesModel);
                        await applicationDbContext.SaveChangesAsync();
                    }
                    if (model.ImageFile == null)
                    {

                        var rates = applicationDbContext.Candidates.FindAsync(id).Result;

                        model.ImageFile = rates.ImageFile;
                        var CandidatesModel = mapper.Map<Candidates>(model);

                        applicationDbContext.Candidates.Update(CandidatesModel);
                        await applicationDbContext.SaveChangesAsync();
                    }

                }
                catch (Exception x)
                {

                }
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }









        public IActionResult Delete(int id)
        {
            var dispatch = new Candidates();

            try
            {
                if (id == 0)
                {
                    return BadRequest();
                }

                dispatch = applicationDbContext.Candidates.FindAsync(id).Result;
                return View(dispatch);
            }
            catch (Exception e)
            {
                logger.LogError(e.Message);
                return BadRequest();
            }

        }

        [HttpPost]
        public async Task<IActionResult> DeleteConfirm(int id)
        {
            var dispatch = new Candidates();

            try
            {
                if (id == 0)
                {
                    return BadRequest();
                }

                dispatch = applicationDbContext.Candidates.FindAsync(id).Result;
                applicationDbContext.Candidates.Remove(dispatch);
                await applicationDbContext.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {
                logger.LogError(e.Message);
                return BadRequest();
            }

        }






        public IActionResult GetAllCandidates()
        {

            try
            {
                var cadidates = applicationDbContext.Candidates.ToList();

                var ratesModel = mapper.Map<IEnumerable<CadidatesViewModel>>(cadidates);


                return Json(ratesModel);
            }
            catch (Exception e)
            {
                //logger.LogError(e.Message);
                return BadRequest();
            }
        }


        [HttpGet]
        public IActionResult AddCandidate()
        {
            CadidatesViewModel movieDetailsViewModel = new CadidatesViewModel();
            _notyf.Information("You are about to ADD a Candidate ", 5);
            return View(movieDetailsViewModel);
        }

        [HttpPost]
        [Obsolete]
        public async Task<IActionResult> AddCandidateAsync(CadidatesViewModel model)
        {
            //Candidates userEntity = new Candidates();

            _notyf.Success("A Candidate was added ", 5);
            if (ModelState.IsValid)
            {
                //Save image to wwwroot/image
                string wwwRootPath = _Environment.WebRootPath;
                string fileName = Path.GetFileNameWithoutExtension(model.ImageFile.FileName);
                string extension = Path.GetExtension(model.ImageFile.FileName);
                model.ImageName = fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                string path = Path.Combine(wwwRootPath + "/Image/", fileName);
                using (var fileStream = new FileStream(path, FileMode.Create))
                {
                    await model.ImageFile.CopyToAsync(fileStream);
                }
                var cadidates = applicationDbContext.Candidates.ToList();

                var CandidatesModel = mapper.Map<Candidates>(model);

                await applicationDbContext.Candidates.AddAsync(CandidatesModel);
                await applicationDbContext.SaveChangesAsync();

                //this is to send data tp the char Js FUNTION/METHOND 
                //await _movieHub.Clients.All.SendAsync("Create", Analytics());

                if (CandidatesModel.Id > 0)
                {
                    return RedirectToAction("index");

                }

            }

            return View(model);

        }


    }
}

Controllers/VoteController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using AutoMapper;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Nust_Vote_System.Datalayer;
using Nust_Vote_System.DatatabaseModel;
using Nust_Vote_System.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Nust_Vote_System.Controllers
{
    public class VoteController : Controller
    {
        private readonly VotingContext applicationDbContext;
        private readonly IMapper mapper;
        private readonly ILogger<AccountController> logger;
        private readonly INotyfService _notyf;
        private IWebHostEnvironment _Environment;

        public VoteController(IWebHostEnvironment Environment, INotyfService notyf, VotingContext applicationDbContext, IMapper mapper, ILogger<AccountController> logger)
        {
            this.applicationDbContext = applicationDbContext;
            this.mapper = mapper;
            this.logger = logger;
            _notyf = notyf;

            _Environment = Environment;
        }

        [HttpGet]
        public IActionResult Index()
        {

            return View();

        }

        public IActionResult Random()
        {

            return View();

        }

        public IActionResult Vote(int id)
        {

            var dispatch = new Candidates();

            try
            {
                if (id == 0)
                {
                    return BadRequest();
                }

                dispatch = applicationDbContext.Candidates.FindAsync(id).Result;
                return View(dispatch);
            }
            catch (Exception e)
            {
                logger.LogError(e.Message);
                return BadRequest();
            }


        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            _notyf.Custom("Deleted a Movie.", 5, "pink", "fas fa-trash-alt");

            var movie = await applicationDbContext.Candidates.FindAsync(id);
            applicationDbContext.Candidates.Remove(movie);
            //movieService.DeleteMovie(id);
            //await _movieHub.Clients.All.SendAsync("Create", Analytics());
            await applicationDbContext.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }


        public IActionResult President()
        {
            CadidatesViewModel movieView = new CadidatesViewModel();
            List<CadidatesViewModel> model = new List<CadidatesViewModel>();
            var rates = applicationDbContext.Candidates.ToList();

            var ratesModel = mapper.Map<IEnumerable<CadidatesViewModel>>(rates);

            CadidatesViewModelList detailsViewModel = new CadidatesViewModelList();


            detailsViewModel.Cadidates = new List<CadidatesViewModel>();


            detailsViewModel.Cadidates = (List<CadidatesViewModel>)ratesModel;

            return View(detailsViewModel);
        }
        public IActionResult VicePresident()
        {
            CadidatesViewModel movieView = new CadidatesViewModel();
            List<CadidatesViewModel> model = new List<CadidatesViewModel>();
            var rates = applicationDbContext.Candidates.ToList();

            var ratesModel = mapper.Map<IEnumerable<CadidatesViewModel>>(rates);

            CadidatesViewModelList detailsViewModel = new CadidatesViewModelList();


            detailsViewModel.Cadidates = new List<CadidatesViewModel>();


            detailsViewModel.Cadidates = (List<CadidatesViewModel>)ratesModel;

            return View(detailsViewModel);
        }


    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]Voting System</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"
          rel="stylesheet" />
    @*cute alert css*@
    <link rel="stylesheet" href="~/lib/cute-alert/style.css" />
    <link rel="stylesheet" href="~/css/toastr.min.css" />
</head>
<body style="background: #F3F3F4;">
    <header style="    background: #1b2c5d;    border-bottom: solid 2px #fcaf17 !important;">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light ">
            <div class="container">
                @*<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index" style="color:white">Nust Voting System</a>*@
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="btn btn-outline-light borderInnit" asp-area="" asp-controller="Home" asp-action="Index">Home</a>&nbsp; &nbsp;
                        </li>
                        <li class="nav-item">
                            <a class="btn btn-outline-light borderInnit" asp-area="" asp-controller="Candidate" asp-action="Index">Candidates</a>&nbsp; &nbsp;
                        </li> 
                        <li class="nav-item">
                            <a class="btn btn-outline-light borderInnit" asp-area="" asp-controller="Vote" asp-action="Index">Vote</a>&nbsp; &nbsp;
                        </li>
                    </ul>
                    @*<partial name="_LoginPartial" />*@
                </div>
            </div>
        </nav>  
    </header>


    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer" style="background: #1b2c5d">
        <div class="container" style="color:white">
            &copy; 2022 - Namibia University of Science and Technology . All Rights Reserved. - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/toastr.min.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>